<a href="https://colab.research.google.com/github/belgaa-a/EksploracjaDanych/blob/main/AW_zajecia1_0810.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Eksploracja danych — Laboratorium 1
## Python do analizy danych: przypomnienie

**Cel zajęć:** odświeżyć Pythona i poznać podstawy narzędzi, których będziemy używać przez cały semestr: **NumPy**, **pandas** i **matplotlib**.

**Plan:**
1. Python w pigułce
2. NumPy
3. pandas — pierwsze kroki
4. Wykresy w matplotlib

**Zadania** mają dwa poziomy:
- 🟢 **podstawowe** — obowiązkowe,
- 🔵 **dla ambitnych** — dodatkowe.

**Jak pracować:** w Colabie wybierz *Plik → Zapisz kopię na Dysku*, rozwiąż zadania w miejscach oznaczonych `# TODO`, a gotowy notatnik umieść w swoim repozytorium na GitHubie.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams.update({"figure.figsize": (7, 4), "font.size": 12})

---
# 1. Python w pigułce

In [3]:
# Listy, indeksowanie i wycinanie (slicing)
temperatury = [12.5, 14.0, 9.8, 17.3, 15.1]

print(temperatury[0])     # pierwszy element
print(temperatury[-1])    # ostatni element
print(temperatury[1:3])   # elementy o indeksach 1 i 2
print(len(temperatury))

12.5
15.1
[14.0, 9.8]
5

In [4]:
# Pętla for, enumerate i zip
dni = ["pon", "wt", "śr", "czw", "pt"]

for i, t in enumerate(temperatury):
    print(f"[{i}] -> {t}")

for dzien, t in zip(dni, temperatury):
    print(f"{dzien}: {t:.1f} °C")   # :.1f — jedna cyfra po przecinku

[0] -> 12.5
[1] -> 14.0
[2] -> 9.8
[3] -> 17.3
[4] -> 15.1
pon: 12.5 °C
wt: 14.0 °C
śr: 9.8 °C
czw: 17.3 °C
pt: 15.1 °C

In [5]:
# Słownik: klucz -> wartość
miasto = {"nazwa": "Łódź", "wojewodztwo": "łódzkie", "ludnosc_2021": 670_642}

print(miasto["nazwa"])
for klucz, wartosc in miasto.items():
    print(klucz, "=", wartosc)

Łódź
nazwa = Łódź
wojewodztwo = łódzkie
ludnosc_2021 = 670642

In [9]:
# Funkcja z docstringiem
def potega(lista, p):
    """
    Podnosi każdy element listy do potęgi p.

    Parametry:
    - lista (list): lista liczb,
    - p (int | float): wykładnik.

    Zwraca:
    - list: nowa lista z elementami podniesionymi do potęgi p.
    """
    wynik = []
    for x in lista:
        wynik.append(x ** p)
    return wynik


print(potega([1, 2, 3, 4], 3))
help(potega)   # w Jupyterze/Colabie także: potega?

[1, 8, 27, 64]
Help on function potega in module __main__:

potega(lista, p)
    Podnosi każdy element listy do potęgi p.

    Parametry:
    - lista (list): lista liczb,
    - p (int | float): wykładnik.

    Zwraca:
    - list: nowa lista z elementami podniesionymi do potęgi p.

### List comprehension

Zwięzły sposób tworzenia list:
```python
[wyrażenie for element in kolekcja if warunek]
```

In [ ]:
print([x ** 2 for x in range(6)])
print([x ** 2 for x in range(6) if x % 2 == 0])

### 🟢 Zadanie 1: średnia i mediana

Lista `dlugosc_zycia` zawiera oczekiwaną długość życia (w latach) w 14 krajach.

1. Napisz funkcję `srednia(liczby)`, która zwraca średnią arytmetyczną — **bez** używania `sum()` i NumPy (użyj pętli).
2. Napisz funkcję `mediana(liczby)`, która zwraca medianę. Pamiętaj o przypadku parzystej i nieparzystej liczby elementów. Wskazówka: `sorted()`.
3. Porównaj wyniki z `np.mean()` i `np.median()`.

🔵 **Dla ambitnych:** niech obie funkcje zgłaszają czytelny błąd (`raise ValueError(...)`), gdy lista jest pusta.

In [ ]:
dlugosc_zycia = [81.8, 81.0, 82.6, 83.0, 81.8, 84.3, 82.8, 81.9, 82.2, 82.0, 82.7, 79.8, 83.3, 82.0]

In [10]:
def srednia(liczby):
    if len(liczby) == 0:
        raise ValueError("Lista nie może być pusta.")
    suma = 0
    for liczba in liczby:
        suma += liczba
    return suma / len(liczby)


def mediana(liczby):
    if len(liczby) == 0:
        raise ValueError("Lista nie może być pusta.")
    posortowane = sorted(liczby)
    n = len(posortowane)
    srodek = n // 2

    if n % 2 == 1:
        return posortowane[srodek]
    return (posortowane[srodek - 1] + posortowane[srodek]) / 2


print("moja średnia:", srednia(dlugosc_zycia), "NumPy:", np.mean(dlugosc_zycia))
print("moja mediana:", mediana(dlugosc_zycia), "NumPy:", np.median(dlugosc_zycia))

moja średnia: 82.22857142857143 NumPy: 82.22857142857143
moja mediana: 82.1 NumPy: 82.1

### 🟢 Zadanie 2: zliczanie

Napisz funkcję `zlicz(lista)`, która zwraca słownik: element → liczba jego wystąpień.

Przykład: `zlicz(["a", "b", "a", "c", "a"])` → `{"a": 3, "b": 1, "c": 1}`

Sprawdź ją na liście `oceny`. Która ocena występuje najczęściej?

In [11]:
oceny = [4, 3, 5, 4, 4, 2, 3, 5, 4, 3, 4, 5, 3, 4]

def zlicz(lista):
    wynik = {}
    for element in lista:
        if element in wynik:
            wynik[element] += 1
        else:
            wynik[element] = 1
    return wynik


print(zlicz(oceny))
print("Najczęściej występuje ocena:", max(zlicz(oceny), key=zlicz(oceny).get))

{4: 6, 3: 4, 5: 3, 2: 1}
Najczęściej występuje ocena: 4

### 🟢 Zadanie 3: list comprehension

Dla listy `temperatury` (w °C) z początku notatnika:

1. Utwórz listę temperatur w stopniach Fahrenheita: $F = \frac{9}{5}C + 32$.
2. Utwórz listę tylko tych temperatur (w °C), które są wyższe niż 13 °C.
3. Utwórz listę napisów w postaci `"pon: 12.5 °C"` (wskazówka: `zip`).

Każdy punkt rozwiąż **jedną** linią.

In [18]:
temperatury_F = [9/5 * C + 32 for C in temperatury]
temperatury_pow_13 = [C for C in temperatury if C > 13]
napisy_temperatur = [f"{dzien}: {temp} °C" for dzien, temp in zip(dni, temperatury)]

print(temperatury_F)
print(temperatury_pow_13)
print(napisy_temperatur)

[54.5, 57.2, 49.64, 63.14, 59.18]
[14.0, 17.3, 15.1]
['pon: 12.5 °C', 'wt: 14.0 °C', 'śr: 9.8 °C', 'czw: 17.3 °C', 'pt: 15.1 °C']

---
# 2. NumPy

**NumPy** to podstawa obliczeń numerycznych w Pythonie — na nim zbudowane są pandas, scikit-learn i wiele innych bibliotek. Kluczowa idea: **wektoryzacja**, czyli operacje na całych tablicach naraz, bez pisania pętli.

In [17]:
a = np.array([1, 2, 3, 4, 5])
print(a, a.dtype, a.shape)

print(np.arange(0, 10, 2))       # od 0 do 10 (bez 10) co 2
print(np.linspace(0, 1, 5))      # 5 równo rozłożonych punktów od 0 do 1 (z 1)
print(np.zeros(3), np.ones(3))

[1 2 3 4 5] int64 (5,)
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0. 0. 0.] [1. 1. 1.]

### Lista ≠ tablica

Te same operatory działają inaczej na listach i na tablicach NumPy:

In [16]:
lista = [1, 2, 3]
tablica = np.array([1, 2, 3])

print("lista * 2   =", lista * 2)      # powtórzenie listy!
print("tablica * 2 =", tablica * 2)    # mnożenie każdego elementu
print("lista + lista     =", lista + lista)        # sklejenie list
print("tablica + tablica =", tablica + tablica)    # dodawanie element po elemencie

lista * 2   = [1, 2, 3, 1, 2, 3]
tablica * 2 = [2 4 6]
lista + lista     = [1, 2, 3, 1, 2, 3]
tablica + tablica = [2 4 6]

In [15]:
# Maski logiczne i agregacje
pomiary = np.array([7, 5, 4, 8, 4, 2, 9, 4, 100])

print("maska > 5:", pomiary > 5)
print("wartości > 5:", pomiary[pomiary > 5])
print("ile > 5:", (pomiary > 5).sum())

print("min, max:", pomiary.min(), pomiary.max())
print("średnia:", pomiary.mean())
print("mediana:", np.median(pomiary))
print("odchylenie standardowe:", pomiary.std())

maska > 5: [ True False False  True False False  True False  True]
wartości > 5: [  7   8   9 100]
ile > 5: 4
min, max: 2 100
średnia: 15.88888888888889
mediana: 5.0
odchylenie standardowe: 29.812169194789657

### Liczby losowe

Używamy **generatora** `np.random.default_rng()`. Ustalone ziarno (`seed`) daje powtarzalne wyniki.

In [14]:
rng = np.random.default_rng(seed=42)

print(rng.integers(1, 7, size=10))        # 10 rzutów kostką: liczby całkowite z [1, 7)
print(rng.uniform(0, 1, size=3))          # 3 liczby z rozkładu jednostajnego na [0, 1)
print(rng.normal(loc=0, scale=1, size=3)) # 3 liczby z rozkładu normalnego N(0, 1)

[1 5 4 3 3 6 1 5 2 1]
[0.97562235 0.7611397  0.78606431]
[-0.01680116 -0.85304393  0.87939797]

### 🟢 Zadanie 4: dlaczego NumPy?

Zsumuj liczby od 1 do 1 000 000 na **cztery sposoby** i zmierz czas każdego z nich magiczną komendą `%timeit`:

1. pętla `for`,
2. `sum()` na liście zbudowanej przez list comprehension,
3. `sum(range(...))`,
4. NumPy: `np.arange(...).sum()`.

Sprawdź, czy wszystkie dają ten sam wynik. Który sposób jest najszybszy i **dlaczego**? Odpowiedz w komórce tekstowej.

In [19]:
N = 1_000_000

def suma_petla(n):
    wynik = 0
    for i in range(1, n + 1):
        wynik += i
    return wynik

def suma_comprehension(n):
    return sum([i for i in range(1, n + 1)])

def suma_range(n):
    return sum(range(1, n + 1))

def suma_numpy(n):
    return np.arange(1, n + 1).sum()

wyniki = [suma_petla(N), suma_comprehension(N), suma_range(N), suma_numpy(N)]
print(wyniki)
print("Wszystkie wyniki są równe:", len(set(wyniki)) == 1)

%timeit suma_petla(N)
%timeit suma_comprehension(N)
%timeit suma_range(N)
%timeit suma_numpy(N)

[500000500000, 500000500000, 500000500000, np.int64(500000500000)]
Wszystkie wyniki są równe: True
40.8 ms ± 446 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
36 ms ± 1.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
12.8 ms ± 2.09 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
532 µs ± 24.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

*Twoja odpowiedź:*

Wszystkie sposowy zwracają tą samą sumę. Najszybszy jest NumPy.
range() nie tworzy całej listy liczb w pamięci, natomiast NumPy wykonuje operacje w zoptymalizowanym kodzie tablicowym.
Kolejność czasów zależy od komputera i środowiska Jupyter.

### 🟢 Zadanie 5: operacje na tablicach

Dana jest tablica `x` z pomiarami temperatury (°C).

1. Policz średnią, odchylenie standardowe, minimum i maksimum.
2. Wybierz pomiary wyższe od średniej. Ile ich jest?
3. **Normalizacja min–max:** przeskaluj `x` do przedziału $[0, 1]$: $\;x' = \dfrac{x - x_{\min}}{x_{\max} - x_{\min}}$
4. **Standaryzacja:** $\;z = \dfrac{x - \bar{x}}{s}$. Sprawdź, że wynik ma średnią ≈ 0 i odchylenie standardowe ≈ 1.

Wszystko bez pętli!

In [20]:
x = np.array([12.5, 14.0, 9.8, 17.3, 15.1, 11.2, 18.6, 16.0, 13.4, 10.9])

srednia_x = np.mean(x)
odchylenie_x = np.std(x)
minimum_x = np.min(x)
maksimum_x = np.max(x)

print("Średnia:", srednia_x)
print("Odchylenie standardowe:", odchylenie_x)
print("Minimum:", minimum_x)
print("Maksimum:", maksimum_x)

powyzej_sredniej = x[x > srednia_x]
print("Pomiary wyższe od średniej:", powyzej_sredniej)
print("Liczba takich pomiarów:", len(powyzej_sredniej))

normalizacja = (x - minimum_x) / (maksimum_x - minimum_x)
print("Normalizacja min-max:", normalizacja)

standaryzacja = (x - srednia_x) / odchylenie_x
print("Standaryzacja:", standaryzacja)
print("Średnia po standaryzacji:", np.mean(standaryzacja))
print("Odchylenie po standaryzacji:", np.std(standaryzacja))

Średnia: 13.88
Odchylenie standardowe: 2.7352513595646015
Minimum: 9.8
Maksimum: 18.6
Pomiary wyższe od średniej: [14.  17.3 15.1 18.6 16. ]
Liczba takich pomiarów: 5
Normalizacja min-max: [0.30681818 0.47727273 0.         0.85227273 0.60227273 0.15909091
 1.         0.70454545 0.40909091 0.125     ]
Standaryzacja: [-0.50452402  0.04387165 -1.49163622  1.25034213  0.44602848 -0.97980026
  1.72561837  0.77506588 -0.17548661 -1.0894794 ]
Średnia po standaryzacji: -1.7763568394002506e-16
Odchylenie po standaryzacji: 1.0

### 🟢 Zadanie 6: rzuty kostką

1. Zasymuluj 10 000 rzutów kostką do gry (`rng.integers`).
2. Policz, ile razy wypadła każda liczba oczek (wskazówka: `np.unique(..., return_counts=True)`) i jaki to odsetek wszystkich rzutów.
3. Policz średnią liczbę oczek. Jakiej wartości się spodziewasz?

🔵 **Dla ambitnych:** zasymuluj 10 000 rzutów **dwiema** kostkami i policz rozkład sumy oczek. Która suma wypada najczęściej i dlaczego?

In [21]:
rng = np.random.default_rng(seed=1)

rzuty = rng.integers(1, 7, size=10_000)

wartosci, liczby = np.unique(rzuty, return_counts=True)
procenty = liczby / len(rzuty) * 100

for wartosc, liczba, procent in zip(wartosci, liczby, procenty):
    print(f"{wartosc}: {liczba} razy ({procent:.2f}%)")

print("Średnia liczba oczek:", np.mean(rzuty))
print("Oczekiwana wartość:", 3.5)

# Dla ambitnych
kostka1 = rng.integers(1, 7, size=10_000)
kostka2 = rng.integers(1, 7, size=10_000)
sumy = kostka1 + kostka2

wartosci_sum, liczby_sum = np.unique(sumy, return_counts=True)
print("Rozkład sum dwóch kostek:")
for wartosc, liczba in zip(wartosci_sum, liczby_sum):
    print(f"{wartosc}: {liczba}")

print("Najczęściej wypadła suma:", wartosci_sum[np.argmax(liczby_sum)])
print("Teoretycznie najczęstsza suma to 7, ponieważ można ją uzyskać na 6 sposobów.")

1: 1695 razy (16.95%)
2: 1634 razy (16.34%)
3: 1668 razy (16.68%)
4: 1628 razy (16.28%)
5: 1717 razy (17.17%)
6: 1658 razy (16.58%)
Średnia liczba oczek: 3.5012
Oczekiwana wartość: 3.5
Rozkład sum dwóch kostek:
2: 287
3: 534
4: 878
5: 1117
6: 1408
7: 1703
8: 1351
9: 1098
10: 821
11: 522
12: 281
Najczęściej wypadła suma: 7
Teoretycznie najczęstsza suma to 7, ponieważ można ją uzyskać na 6 sposobów.

---
# 3. pandas — pierwsze kroki

**pandas** służy do pracy z danymi tabelarycznymi. Podstawowe struktury:
- `Series` — jedna kolumna (wektor z etykietami),
- `DataFrame` — tabela, czyli zbiór kolumn o wspólnym indeksie.

### DataFrame ze słownika

In [22]:
dane = {
    "miasto": ["Warszawa", "Kraków", "Łódź", "Wrocław", "Poznań"],
    "ludnosc_2021": [1_860_281, 800_653, 670_642, 674_079, 546_859],
    "powierzchnia_km2": [517, 327, 293, 293, 262],
}
miasta = pd.DataFrame(dane)
miasta

     miasto  ludnosc_2021  powierzchnia_km2
0  Warszawa       1860281               517
1    Kraków        800653               327
2      Łódź        670642               293
3   Wrocław        674079               293
4    Poznań        546859               262

In [23]:
# Nowa kolumna obliczona z innych kolumn
miasta["gestosc"] = miasta["ludnosc_2021"] / miasta["powierzchnia_km2"]
miasta.sort_values("gestosc", ascending=False)

     miasto  ludnosc_2021  powierzchnia_km2      gestosc
0  Warszawa       1860281               517  3598.222437
1    Kraków        800653               327  2448.480122
3   Wrocław        674079               293  2300.610922
2      Łódź        670642               293  2288.880546
4    Poznań        546859               262  2087.248092

In [24]:
# Zapis do pliku CSV i ponowne wczytanie
miasta.to_csv("miasta.csv", index=False)
pd.read_csv("miasta.csv")

     miasto  ludnosc_2021  powierzchnia_km2      gestosc
0  Warszawa       1860281               517  3598.222437
1    Kraków        800653               327  2448.480122
2      Łódź        670642               293  2288.880546
3   Wrocław        674079               293  2300.610922
4    Poznań        546859               262  2087.248092

### Prawdziwy zbiór danych: `tips`

Zbiór `tips` zawiera 244 rachunki z restauracji, zapisane przez kelnera w ciągu kilku tygodni.

| kolumna | znaczenie |
|---|---|
| `total_bill` | kwota rachunku (USD) |
| `tip` | napiwek (USD) |
| `sex` | płeć płacącego |
| `smoker` | czy przy stoliku palono |
| `day` | dzień tygodnia |
| `time` | pora: lunch / obiad |
| `size` | liczba osób przy stoliku |

In [25]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Pierwszy rzut oka na dane

In [26]:
print(df.shape)     # (liczba wierszy, liczba kolumn)
df.info()           # typy kolumn i liczba niepustych wartości

(244, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [27]:
df.describe()       # statystyki opisowe kolumn liczbowych

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

### Wybieranie kolumn i wierszy

In [28]:
df["tip"].head()                    # jedna kolumna -> Series

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [29]:
df[["total_bill", "tip"]].head()    # kilka kolumn -> DataFrame (podwójne nawiasy!)

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50
3       23.68  3.31
4       24.59  3.61

In [30]:
print(df["tip"].mean(), df["tip"].max())   # metody kolumny

2.99827868852459 10.0

### `loc` czy `iloc`?

- `iloc` — wybiera po **pozycji** (0, 1, 2, …),
- `loc` — wybiera po **etykiecie indeksu**.

Póki indeks to 0, 1, 2, …, oba dają to samo. Różnica wychodzi na jaw po posortowaniu:

In [ ]:
posortowane = df.sort_values("tip", ascending=False)
posortowane.head(3)

In [ ]:
print("iloc[0] — pierwszy wiersz po posortowaniu (najwyższy napiwek):")
print(posortowane.iloc[0], "\n")

print("loc[0] — wiersz o etykiecie 0 (pierwszy rachunek w danych):")
print(posortowane.loc[0])

### Filtrowanie

Warunki łączymy operatorami `&` (i), `|` (lub), `~` (nie) — każdy warunek **w nawiasach**.

In [ ]:
duze_rachunki = df[df["total_bill"] > 40]
duze_rachunki

In [ ]:
sobota_obiad = df[(df["day"] == "Sat") & (df["time"] == "Dinner")]
print(len(sobota_obiad), "rachunków w sobotę na obiedzie")

In [ ]:
# Z .loc: wiersze spełniające warunek i wybrane kolumny
df.loc[df["size"] >= 5, ["total_bill", "tip", "size"]]

In [ ]:
df["day"].value_counts()    # ile razy występuje każda wartość

### 🟢 Zadanie 7: pytania do zbioru `tips`

Odpowiedz kodem:

1. Ile wierszy i kolumn ma zbiór? Jakie są nazwy kolumn?
2. Jaki jest średni, najmniejszy i największy rachunek?
3. Ile rachunków pochodzi z niedzieli (`"Sun"`)?
4. Pokaż 5 najwyższych rachunków.
5. Dodaj kolumnę `tip_pct` — napiwek jako procent rachunku. Jaki jest średni `tip_pct`?
6. Ile rachunków ma napiwek wyższy niż 20% rachunku?

🔵 **Dla ambitnych:**

7. Jaki jest średni `tip_pct` dla lunchu, a jaki dla obiadu? (Użyj filtrowania.)
8. Dodaj kolumnę `rachunek_na_osobe`. Przy którym stoliku rachunek na osobę był najwyższy?

In [31]:
print("Wymiary:", df.shape)
print("Nazwy kolumn:", df.columns.tolist())

print("\nRachunki:")
print("Średni:", df["total_bill"].mean())
print("Najmniejszy:", df["total_bill"].min())
print("Największy:", df["total_bill"].max())

print("\nLiczba rachunków w niedzielę:", (df["day"] == "Sun").sum())

print("\n5 najwyższych rachunków:")
print(df.nlargest(5, "total_bill"))

df["tip_pct"] = df["tip"] / df["total_bill"] * 100
print("\nŚredni tip_pct:", df["tip_pct"].mean())
print("Rachunki z napiwkiem > 20%:", (df["tip_pct"] > 20).sum())

print("\nŚredni tip_pct — Lunch:", df.loc[df["time"] == "Lunch", "tip_pct"].mean())
print("Średni tip_pct — Dinner:", df.loc[df["time"] == "Dinner", "tip_pct"].mean())

df["rachunek_na_osobe"] = df["total_bill"] / df["size"]
najwyzszy = df.loc[df["rachunek_na_osobe"].idxmax()]
print("\nNajwyższy rachunek na osobę:")
print(najwyzszy[["total_bill", "size", "rachunek_na_osobe"]])

Wymiary: (244, 7)
Nazwy kolumn: ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

Rachunki:
Średni: 19.78594262295082
Najmniejszy: 3.07
Największy: 50.81

Liczba rachunków w niedzielę: 76

5 najwyższych rachunków:
     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

Średni tip_pct: 16.08025817225047
Rachunki z napiwkiem > 20%: 39

Średni tip_pct — Lunch: 16.412792816250498
Średni tip_pct — Dinner: 15.951778877977734

Najwyższy rachunek na osobę:
total_bill            40.55
size                      2
rachunek_na_osobe    20.275
Name: 184, dtype: object